name: flutter_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.4
  google_sign_in_platform_interface: ^2.4.0
  google_sign_in_web: ^0.12.0+5
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  provider: ^6.0.4
  go_router: ^12.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
