name: flutter_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: 0.13.5
  provider: ^6.0.4
  infinite_scroll_pagination: ^3.2.0
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
