version: "3.7"

networks:
  proxy-network:
    name: ${PROXY_NETWORK}
    external: true
  coin-library-network:
    name: coin-library-network
    external: false

services:
  backend:
    container_name: coin_library_backend
    image: ${DOCKERHUB_USER}/dcl_backend:${ENVIRONMENT}
    ports:
      - "9010:8080"
    depends_on:
      - database
    networks:
      - coin-library-network
      - proxy-network

  database:
    container_name: coin_library_database
    image: mariadb:10.9.3
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ${DATABASE_MOUNT}/data:/var/lib/mysql
      - ${DATABASE_MOUNT}/conf:/etc/mysql
    ports:
      - "3306:3306"
    networks:
      - coin-library-network

  frontend:
    container_name: coin_library_frontend
    image: ${DOCKERHUB_USER}/dcl_frontend:${ENVIRONMENT}
    ports:
      - "9013:80"
    networks:
      -  proxy-network