version: "3.7"

include:
  - docker-compose-base.yml

services:
  selenium:
    container_name: coin_library_selenium
    image: seleniarm/standalone-chromium:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4445:4444"
      - "7900:7900"
    networks:
      - coin-library-network