spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/digital_coin_library
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
        provider:
          google:
            token-uri: https://www.googleapis.com/oauth2/v4/token
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      resourceserver:
        opaquetoken:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          introspection-uri: https://oauth2.googleapis.com/tokeninfo
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v2/certs
          issuer-uri: https://accounts.google.com
logging:
  config:
    classpath: logback.xml
  level:
    root: debug
    org:
      springframework:
        security: DEBUG
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


#Custom Parameters
app:
  selenium:
    url: http://127.0.0.1
    port: 4445
  frontend:
    url: ${FRONTEND_URL}
  backend:
    username: ${SPRING_USERNAME}
    password: ${SPRING_PASSWORD}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}