spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/${MARIADB_DATABASE}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

logging:
  config:
    classpath: logback.xml
  level:
    root: debug
    org:
      springframework:
        security: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


#Custom Parameters
app:
  selenium:
    url: http://127.0.0.1
    port: 4445
  frontend:
    url: ${FRONTEND_URL}
  backend:
    username: ${SPRING_USERNAME}
    password: ${SPRING_PASSWORD}
google:
  client:
    id: ${GOOGLE_CLIENT_ID}