on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      ref:
        required: true
        type: string
        default: ${{ github.head_ref }}

jobs:
  checkout_repository:
    name: Checkout Repository
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}