name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    name: Deploy Production
    uses:
      tstelzle/DigitalCoinLibrary/.github/workflows/deploy.yml@main
    with:
      runner: prod
      environment: production
    secrets: inherit