name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  checkout_repository:
    name: Checkout Repository
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  create_env_file:
    name: Create Environment File
    runs-on: self-hosted
    steps:
      - name: Create Environment File
        run: touch coin_library.env

      - name: Add DB User
        env:
          MARIADB_USER: ${{ secrets.MARIADB_USER }}
        run: echo "MARIADB_USER=$MARIADB_USER" >> coin_library.env

      - name: Add DB Password
        env:
          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
        run: echo "MARIADB_PASSWORD=$MARIADB_PASSWORD" >> coin_library.env

      - name: Add DB Root Password
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
        run: echo "MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD" >> coin_library.env

      - name: Add API URL
        env:
          API_URL: ${{ secrets.API_URL }}
        run: echo "API_URL=$API_URL" >> coin_library.env

      - name: Add API PORT
        env:
          API_PORT: ${{ secrets.API_PORT }}
        run: echo "API_PORT=$API_PORT" >> coin_library.env

      - name: Add DATABASE MOUNT
        env:
          DATABASE_MOUNT: ${{ secrets.DATABASE_MOUNT }}
        run: echo "DATABASE_MOUNT=$DATABASE_MOUNT" >> coin_library.env

      - name: Create DATABASE MOUNT
        env:
          DATABASE_MOUNT: ${{ secrets.DATABASE_MOUNT }}
        run: mkdir -p $DATABASE_MOUNT

  build_backend:
    needs: [ checkout_repository, create_env_file]
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Build Dockerfile
        run: docker-compose --env-file coin_library.env build --no-cache backend

  build_frontend:
    needs: [ checkout_repository, create_env_file]
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Build Dockerfile
        run: docker-compose --env-file coin_library.env build --no-cache frontend

  run_application:
    needs: [ build_backend, build_frontend ]
    name: Run Application
    environment: production
    runs-on: self-hosted
    steps:
      - name: Run Application
        run: docker-compose --env-file coin_library.env up -d