name: Deploy Production

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  checkout-repository:
    name: Checkout Repository
    runs-on: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  call-create-file:
    needs: [ checkout-repository ]
    name: Call Create Environment File
    runs-on: prod
    steps:
      - name: Run Create Environment File
        run: ./.github/workflows/create_env.yml
        with:
          runner: prod
          env: production

  call-build-file:
    needs: [ call-create-file ]
    name: Call Build File
    runs-on: prod
    steps:
      - name: Run Build
        run: ./.github/workflows/build.yml
        with:
          runner: prod

  call-run-file:
    needs: [ call-build-file ]
    name: Call Run File
    runs-on: prod
    steps:
      - name: Run Run
        run: ./.github/workflows/run.yml
        with:
          runner: prod





