name: Deploy Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  checkout-repository:
    name: Checkout Repository
    runs-on: develop
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  call-create-file:
    needs: [ checkout-repository ]
    name: Call Create Environment File
    runs-on: develop
    steps:
      - name: Run Create Environment File
        run: ./.github/workflows/create_env.yml

  call-build-file:
    needs: [ call-create-file ]
    name: Call Build File
    runs-on: develop
    steps:
      - name: Run Build
        run: ./.github/workflows/build.yml

  call-run-file:
    needs: [ call-build-file ]
    name: Call Run File
    runs-on: develop
    steps:
      - name: Run Run
        run: ./.github/workflows/run.yml





