name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    name: Deploy Production
    uses:
      tstelzle/DigitalCoinLibrary/.github/workflows/deploy.yml@main
    with:
      environment-var: prod
      secrets_environment-var: production