name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    name: Deploy Production
    environment: production
    uses:
      tstelzle/DigitalCoinLibrary/.github/workflows/deploy.yml@main
    with:
      environment: prod
    secrets: inherit