name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop:
    name: Deploy Develop
    uses:
      tstelzle/DigitalCoinLibrary/.github/workflows/deploy.yml@develop
    with:
      runner: develop
      environment: development
    secrets: inherit