name: Run Application

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

run_application:
  name: Run Application
  runs-on: runner
  steps:
    - name: Run Application
      run: docker-compose --env-file coin_library.env up -d